//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Shared.Resources.EmailMessages", typeof(EmailMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string VerificationEmailBody {
            get {
                return ResourceManager.GetString("VerificationEmailBody", resourceCulture);
            }
        }
        
        public static string VerificationEmailSubject {
            get {
                return ResourceManager.GetString("VerificationEmailSubject", resourceCulture);
            }
        }
        
        public static string ResetEmailEmailBody {
            get {
                return ResourceManager.GetString("ResetEmailEmailBody", resourceCulture);
            }
        }
        
        public static string ResetEmailEmailSubject {
            get {
                return ResourceManager.GetString("ResetEmailEmailSubject", resourceCulture);
            }
        }
        
        public static string ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        public static string ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        public static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        public static string ForgotPasswordEmailBody {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailBody", resourceCulture);
            }
        }
    }
}
