// <auto-generated />
using System;
using AudioEngineersPlatformBackend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioEngineersPlatformBackend.Infrastructure.Migrations
{
    [DbContext(typeof(EngineersPlatformDbContext))]
    [Migration("20250806110637_AddFtsIndexForAdvert")]
    partial class AddFtsIndexForAdvert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.Property<Guid>("IdAdvert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoverImageKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAdvertCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAdvertLog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdvert")
                        .HasName("PK_Advert");

                    b.HasIndex("IdAdvertCategory");

                    b.HasIndex("IdAdvertLog");

                    b.HasIndex("IdUser");

                    b.ToTable("Advert", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvert = new Guid("31ba89aa-f10f-40e7-b4b0-7375da567997"),
                            CoverImageKey = new Guid("df0f7b35-b8c2-4246-b7f7-ccc82d4a3a7e"),
                            Description = "With over 10 years of hands-on experience in music mixing, I meticulously balance every element of your track—from drums and bass to vocals and effects—to ensure a polished, radio-ready sound. I use industry-standard tools and reference mixes to match the tonal character and loudness of top-charting songs. Whether you need depth, clarity, or that modern “in-your-face” sheen, I’ll tailor my approach to your genre and artistic vision. Turn your rough stems into a cohesive, dynamic mix that translates across all playback systems.",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("1b84601e-e225-4e9d-93d2-911fb0a1569e"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DZ06evO4pPsgW?si=e069a7940cc7419b",
                            Price = 350.0,
                            Title = "I will mix your song professionally!"
                        },
                        new
                        {
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            CoverImageKey = new Guid("17cf17e7-cf1d-4239-ba5a-5f8484191038"),
                            Description = "Piotr brings 5+ years of mixing expertise in genres ranging from indie rock to electronic dance. He begins each project by analyzing your reference tracks and customizing EQ, compression, and spatial effects to enhance clarity and impact. His workflow includes detailed vocal tuning, side-chain ducking for punchy rhythms, and analog emulation for warm, musical saturation. Expect thorough revision rounds and clear communication every step of the way. Let Piotr transform your raw sessions into a powerful, polished mix that stands out on streaming platforms and live stages alike.",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("a9e9762a-2a67-46f3-b371-50405a100d58"),
                            IdUser = new Guid("2254933a-66ac-4ab8-a923-25d508d8b5c0"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd?si=123456abcdef",
                            Price = 400.0,
                            Title = "Professional mixing services by Piotr"
                        },
                        new
                        {
                            IdAdvert = new Guid("7bfd7cfa-5fde-42e2-ac56-9ee1040b708f"),
                            CoverImageKey = new Guid("2de15e61-0ab9-49eb-b5e2-cf909809d22f"),
                            Description = "Ewa specializes in mastering both digital and analog formats, delivering loudness-optimized masters without sacrificing dynamic range. She uses high-resolution metering and custom multiband compression to sculpt frequencies, tame harshness, and add that final sheen. Your track will be delivered in multiple formats (WAV, MP3, DDP) with ISRC embedding and CD-ready files if needed. Ewa also provides detailed EQ and loudness reports so you know exactly how your music will perform on Spotify, Apple Music, and vinyl pressings. Bring your mixes to the next level with transparent, professional mastering.",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("b3d2dce1-a858-4312-937d-c56a6e0178cf"),
                            IdUser = new Guid("731c7617-9342-415d-8e06-f77ec2d56786"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWTcaP2wCKa4K?si=abcdef123456",
                            Price = 300.0,
                            Title = "Mastering expertise by Ewa"
                        },
                        new
                        {
                            IdAdvert = new Guid("8370e2eb-2ea0-4c4e-99e5-b9e719427f03"),
                            CoverImageKey = new Guid("cedfe8a0-0a9f-4c4a-a50f-76f9fcac396f"),
                            Description = "Tomasz offers end-to-end music production: from songwriting support and beat programming to arrangement and mix-ready stems. He crafts custom drum patterns, bass lines, and melodic hooks tailored to your style. Using both software synths and hardware outboard gear, he delivers a modern, dynamic sound that stands out in today’s crowded market. Each package includes at least three revision rounds, MIDI files for your own tweaks, and guidance on vocals and performance recording. Ideal for solo artists, bands, and labels seeking a cohesive sonic identity.",
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            IdAdvertLog = new Guid("efe85186-52c9-4c46-b585-d4b47523db47"),
                            IdUser = new Guid("29d1d9bd-87d9-4125-99a5-0f15c9df3a30"),
                            PortfolioUrl = "https://open.spotify.com/playlist/4nZo2X8iHrwhYBYdKvysgI",
                            Price = 800.0,
                            Title = "Full production package from Tomasz"
                        },
                        new
                        {
                            IdAdvert = new Guid("8cb96d43-a8a9-4010-8613-f721ecedb8b3"),
                            CoverImageKey = new Guid("0c318716-7c49-4735-9ce2-9eb499377e8a"),
                            Description = "Michał combines both in-the-box precision and analog warmth to achieve a balanced, lively mix. He employs gain-riding automation, mid/side processing, and parallel compression to bring out the emotion in your performance. With fluency across Pro Tools, Logic Pro, and Ableton Live, he adapts to your session templates and plugin suites seamlessly. You’ll receive detailed session notes, dry/wet stems, and high-resolution WAV master ready for distribution. Whether it’s a cinematic score or an underground hip-hop track, Michał’s mixes translate beautifully across car stereos, club systems, and earbuds.",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("24ba6029-f88c-4b12-9a63-bf00c2d9f3e4"),
                            IdUser = new Guid("3fb9e066-38b7-42ae-900c-d7ab5ae280f0"),
                            PortfolioUrl = "https://open.spotify.com/playlist/3eoncc59w7c8t1PnKtSOh6",
                            Price = 450.0,
                            Title = "Advanced mixing workflows by Michał"
                        },
                        new
                        {
                            IdAdvert = new Guid("18809be2-b063-4ada-a7a4-81f9fa107322"),
                            CoverImageKey = new Guid("504cd9ce-5804-4f76-b6bf-706aae87a1b0"),
                            Description = "Katarzyna offers specialized mastering for both vinyl pressings and digital platforms. She carefully sequences tracks, applies EQ to prevent low-end overmodulation, and optimizes side-chain compression for needle-friendly dynamics. For streaming masters, she fine-tunes loudness to meet platform standards (Spotify, Apple Music, Tidal) while preserving headroom and musicality. You’ll get final masters in DDP, WAV, and MP3 formats, plus an analytical Loudness Unit Full Scale (LUFS) report. Elevate your project with a mastering engineer who understands the nuances of different playback mediums.",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("fe0d1832-793e-4cf8-983a-bbe09d7e0fa2"),
                            IdUser = new Guid("ac89f1a4-6988-4211-8136-fbf9b45e4cf2"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DX4WYpdgoIcn6?si=abcd3456ef90",
                            Price = 320.0,
                            Title = "Mastering for vinyl & streaming—Katarzyna"
                        },
                        new
                        {
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            CoverImageKey = new Guid("ef11919d-3e86-4c08-a594-03800f613fd8"),
                            Description = "Krzysztof specializes in crafting genre-blending beats—from trap and lo-fi to funk and soul. Each beat comes with full MIDI programming, drum samples, and multitrack stems so you can rearrange or remix at will. He also offers vocal comping and editing as an add-on, ensuring your performance sits perfectly in the groove. Expect high-quality WAVs, labeled session files, and a quick turnaround. Perfect for rappers, singers, and producers looking for fresh, customizable sound beds.",
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            IdAdvertLog = new Guid("993648ca-9d51-419a-85e8-046e8fc3162b"),
                            IdUser = new Guid("07434fd4-3450-4a01-a8c4-c371ed011e48"),
                            PortfolioUrl = "https://open.spotify.com/playlist/2UZk7JjJnbTut1w8fqs3JL",
                            Price = 900.0,
                            Title = "Beat production & stems by Krzysztof"
                        },
                        new
                        {
                            IdAdvert = new Guid("33545021-1ffb-4f46-9df8-6242b8f0786f"),
                            CoverImageKey = new Guid("d98dd161-cd11-4397-b6b2-48a5656c20a3"),
                            Description = "Agnieszka takes a surgical approach to mixing: corrective EQ, transparent compression, and creative spatial effects that serve your song. She communicates clearly, providing time-stamped revision notes and A/B comparisons. Using analog summing and high-end outboard gear, she injects warmth and depth, then returns to the box for final automation rides. You receive both instrumental and vocal stems plus a mastered reference for quick upload. Ideal for artists who demand both technical accuracy and emotional impact in their mixes.",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("c8ab7e20-e7dd-4616-8862-d15dad3c986a"),
                            IdUser = new Guid("e07bc534-3324-4af4-8d97-faee7242e896"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWXRqgorJj26U?si=4567abcd1234",
                            Price = 480.0,
                            Title = "Mix engineering—Agnieszka’s precision approach"
                        },
                        new
                        {
                            IdAdvert = new Guid("a79c87d0-276b-48bd-b23c-9af67afd4c41"),
                            CoverImageKey = new Guid("c2363242-295c-4435-867c-90d9b96b085a"),
                            Description = "Paweł provides a full delivery package: mastered WAV, high-quality MP3, and separated stems for remixers or video post-production. He focuses on dynamic control, spectral balance, and proper headroom for broadcast. He also embeds metadata (ISRC, artist name, album art) so you can deliver directly to digital distributors with confidence. Comprehensive test masters are supplied so you can preview on headphones, car, and club systems. Get radio-ready masters that truly represent your artistic vision.",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("70820368-d390-4c01-af1f-9e7b8e8413d2"),
                            IdUser = new Guid("1d31a511-8d38-4223-96a0-f2b15cc90794"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWY4xHQp97fN6?si=bcdef7890123",
                            Price = 350.0,
                            Title = "Mastering & delivery by Paweł"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", b =>
                {
                    b.Property<Guid>("IdAdvertCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdvertCategory")
                        .HasName("PK_AdvertCategory");

                    b.ToTable("AdvertCategory", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            CategoryName = "Mixing"
                        },
                        new
                        {
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            CategoryName = "Mastering"
                        },
                        new
                        {
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            CategoryName = "Production"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", b =>
                {
                    b.Property<Guid>("IdAdvertLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdAdvertLog")
                        .HasName("PK_AdvertLog");

                    b.ToTable("AdvertLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvertLog = new Guid("1b84601e-e225-4e9d-93d2-911fb0a1569e"),
                            DateCreated = new DateTime(2024, 2, 3, 12, 35, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("a9e9762a-2a67-46f3-b371-50405a100d58"),
                            DateCreated = new DateTime(2024, 5, 14, 15, 51, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("b3d2dce1-a858-4312-937d-c56a6e0178cf"),
                            DateCreated = new DateTime(2025, 2, 6, 17, 35, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("efe85186-52c9-4c46-b585-d4b47523db47"),
                            DateCreated = new DateTime(2025, 5, 3, 12, 5, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("24ba6029-f88c-4b12-9a63-bf00c2d9f3e4"),
                            DateCreated = new DateTime(2026, 6, 12, 9, 23, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("fe0d1832-793e-4cf8-983a-bbe09d7e0fa2"),
                            DateCreated = new DateTime(2025, 6, 23, 22, 25, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("993648ca-9d51-419a-85e8-046e8fc3162b"),
                            DateCreated = new DateTime(2025, 6, 13, 23, 12, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("c8ab7e20-e7dd-4616-8862-d15dad3c986a"),
                            DateCreated = new DateTime(2025, 4, 3, 12, 11, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("70820368-d390-4c01-af1f-9e7b8e8413d2"),
                            DateCreated = new DateTime(2025, 5, 13, 6, 22, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAdvert")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReviewLog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SatisfactionLevel")
                        .HasColumnType("tinyint");

                    b.HasKey("IdReview")
                        .HasName("PK_Review");

                    b.HasIndex("IdAdvert");

                    b.HasIndex("IdReviewLog");

                    b.HasIndex("IdUser");

                    b.ToTable("Review", (string)null);

                    b.HasData(
                        new
                        {
                            IdReview = new Guid("dbe3112c-8914-44b1-8011-d58cb2ba4270"),
                            Content = "I feel like the engineer could not really achieve what I have wanted, however I think they were really patient and creative ;)",
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            IdReviewLog = new Guid("d9de48fd-0abc-4b52-8371-f9f6959fdc46"),
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            SatisfactionLevel = (byte)3
                        },
                        new
                        {
                            IdReview = new Guid("f88cb211-6464-4b28-aa48-75f257624d86"),
                            Content = "Excellent mixes, I have never worked with such a talented engineer in my life. I will recommend working with him all the way!",
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            IdReviewLog = new Guid("1f642c35-dbfb-4062-ae75-7cf0e3f27f6f"),
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("649406c7-a59a-4102-b7cb-c39d16bc7117"),
                            Content = "They way I was treated was great. I will most definitely visit this engineer in the studio again!",
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            IdReviewLog = new Guid("9473bb77-cff3-42d7-bd0e-2807aa2fef52"),
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("fbd98612-7ccd-4b83-afaa-7084e758e746"),
                            Content = "Poor judgement, does not understand the music I like and hates on doing some additional revisions of a master, I can't recommend this person...",
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            IdReviewLog = new Guid("0d38bc51-218b-4e12-8e39-6bef8654419b"),
                            IdUser = new Guid("655887cb-b3cd-40da-b2bb-48b5e84239f9"),
                            SatisfactionLevel = (byte)1
                        },
                        new
                        {
                            IdReview = new Guid("2d7fe610-9fb0-4a8e-923c-2f7a8afe2a78"),
                            Content = "I feel like this person knows their craft and is capable of delivering a good mix. I can most definitely recommend working with them :)",
                            IdAdvert = new Guid("7bfd7cfa-5fde-42e2-ac56-9ee1040b708f"),
                            IdReviewLog = new Guid("39cc7997-692f-40f4-a3ec-68b00940f6a6"),
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            SatisfactionLevel = (byte)4
                        },
                        new
                        {
                            IdReview = new Guid("5f3bcc4b-d484-44cc-baa2-339373b7d0f0"),
                            Content = "Great production skills, I am very happy with the final result!",
                            IdAdvert = new Guid("8370e2eb-2ea0-4c4e-99e5-b9e719427f03"),
                            IdReviewLog = new Guid("60bb7ac9-88de-4bd4-933b-ce3e71d9cb45"),
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6"),
                            Content = "The mix was good, but I expected more attention to detail. Overall, a decent experience.",
                            IdAdvert = new Guid("31ba89aa-f10f-40e7-b4b0-7375da567997"),
                            IdReviewLog = new Guid("3461a295-b612-4526-aaf1-205ea3a6beff"),
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            SatisfactionLevel = (byte)3
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("IdReviewLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdReviewLog")
                        .HasName("PK_ReviewLog");

                    b.ToTable("ReviewLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdReviewLog = new Guid("d9de48fd-0abc-4b52-8371-f9f6959fdc46"),
                            DateCreated = new DateTime(2025, 3, 13, 15, 48, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("1f642c35-dbfb-4062-ae75-7cf0e3f27f6f"),
                            DateCreated = new DateTime(2025, 5, 7, 13, 23, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("9473bb77-cff3-42d7-bd0e-2807aa2fef52"),
                            DateCreated = new DateTime(2025, 4, 17, 22, 21, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("0d38bc51-218b-4e12-8e39-6bef8654419b"),
                            DateCreated = new DateTime(2025, 4, 29, 21, 17, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("39cc7997-692f-40f4-a3ec-68b00940f6a6"),
                            DateCreated = new DateTime(2025, 2, 16, 13, 11, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("60bb7ac9-88de-4bd4-933b-ce3e71d9cb45"),
                            DateCreated = new DateTime(2025, 5, 26, 15, 42, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("3461a295-b612-4526-aaf1-205ea3a6beff"),
                            DateCreated = new DateTime(2025, 4, 24, 19, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRole")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            RoleName = "Administrator"
                        },
                        new
                        {
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            RoleName = "Client"
                        },
                        new
                        {
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            RoleName = "Audio engineer"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaLink", b =>
                {
                    b.Property<Guid>("IdSocialMediaLink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSocialMediaName")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocialMediaLink")
                        .HasName("PK_SocialMediaLink");

                    b.HasIndex("IdSocialMediaName");

                    b.HasIndex("IdUser");

                    b.ToTable("SocialMediaLink", (string)null);

                    b.HasData(
                        new
                        {
                            IdSocialMediaLink = new Guid("8c0d3528-e2cb-430a-bfd4-8e0623c714cf"),
                            IdSocialMediaName = new Guid("02c8722f-dccc-4060-bec3-c95815c67703"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.instagram.com/prod.mustang/"
                        },
                        new
                        {
                            IdSocialMediaLink = new Guid("7667e3a7-e8f9-4049-af10-a0a405dacf40"),
                            IdSocialMediaName = new Guid("371dbd6d-76eb-4266-aaa3-2b431c5cbafe"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.facebook.com/prod.mustangg/"
                        },
                        new
                        {
                            IdSocialMediaLink = new Guid("b5b570dd-43c8-471e-976b-91a0d50de9f5"),
                            IdSocialMediaName = new Guid("4639c978-26fc-4027-b036-3fc5c0d1d221"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.linkedin.com/in/stanisław-stepka/"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", b =>
                {
                    b.Property<Guid>("IdSocialMediaName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSocialMediaName")
                        .HasName("PK_SocialMediaName");

                    b.ToTable("SocialMediaName", (string)null);

                    b.HasData(
                        new
                        {
                            IdSocialMediaName = new Guid("02c8722f-dccc-4060-bec3-c95815c67703"),
                            Name = "Instagram"
                        },
                        new
                        {
                            IdSocialMediaName = new Guid("371dbd6d-76eb-4266-aaa3-2b431c5cbafe"),
                            Name = "Facebook"
                        },
                        new
                        {
                            IdSocialMediaName = new Guid("4639c978-26fc-4027-b036-3fc5c0d1d221"),
                            Name = "Linkedin"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUserLog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser")
                        .HasName("PK_User");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_User_ForCheckAuth");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IdUser"), new[] { "Email", "FirstName", "LastName", "PhoneNumber", "IdRole" });

                    b.HasIndex("IdUserLog");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("aebc2724-0edf-4691-99e9-65cbd3aab3bf"),
                            Email = "dominik.kow@gmail.com",
                            FirstName = "Dominik",
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            IdUserLog = new Guid("5cb8efaa-2432-46d1-9984-b41a40bab7b3"),
                            LastName = "Kowalski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48123456789"
                        },
                        new
                        {
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            Email = "jan.nowak@gmail.com",
                            FirstName = "Jan",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserLog = new Guid("2f765163-6728-48bc-9767-66687efdf86e"),
                            LastName = "Nowak",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48696432123"
                        },
                        new
                        {
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Email = "anna.kow@gmail.com",
                            FirstName = "Anna",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("8312d4fd-fe6d-4001-a037-cde12000161d"),
                            LastName = "Kowalska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48543123123"
                        },
                        new
                        {
                            IdUser = new Guid("2254933a-66ac-4ab8-a923-25d508d8b5c0"),
                            Email = "piotr.nowak@example.com",
                            FirstName = "Piotr",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("e7653083-1497-4aa0-a56b-dec32a61d71f"),
                            LastName = "Nowak",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111222333"
                        },
                        new
                        {
                            IdUser = new Guid("731c7617-9342-415d-8e06-f77ec2d56786"),
                            Email = "ewa.maj@example.com",
                            FirstName = "Ewa",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("9ae2c2f3-4ab1-4512-9832-7649d5ff61d8"),
                            LastName = "Maj",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111333444"
                        },
                        new
                        {
                            IdUser = new Guid("29d1d9bd-87d9-4125-99a5-0f15c9df3a30"),
                            Email = "tomasz.zielinski@example.com",
                            FirstName = "Tomasz",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("5091bf83-df7d-4a54-a35b-31b44d1a1643"),
                            LastName = "Zieliński",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111444555"
                        },
                        new
                        {
                            IdUser = new Guid("3fb9e066-38b7-42ae-900c-d7ab5ae280f0"),
                            Email = "michal.wojcik@example.com",
                            FirstName = "Michał",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("df0a8813-0938-42a6-ac84-26298701f456"),
                            LastName = "Wójcik",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111555666"
                        },
                        new
                        {
                            IdUser = new Guid("ac89f1a4-6988-4211-8136-fbf9b45e4cf2"),
                            Email = "katarzyna.wisniewska@example.com",
                            FirstName = "Katarzyna",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("2a019dc8-fe9f-4a63-b692-49e03f889f7f"),
                            LastName = "Wiśniewska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111666777"
                        },
                        new
                        {
                            IdUser = new Guid("07434fd4-3450-4a01-a8c4-c371ed011e48"),
                            Email = "krzysztof.lewandowski@example.com",
                            FirstName = "Krzysztof",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("c91c99ca-fffd-42a5-9e6e-fa67d3c0f762"),
                            LastName = "Lewandowski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111777888"
                        },
                        new
                        {
                            IdUser = new Guid("e07bc534-3324-4af4-8d97-faee7242e896"),
                            Email = "agnieszka.wrobel@example.com",
                            FirstName = "Agnieszka",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("8db9e713-d6f0-4f34-b348-c7da0c1a51d6"),
                            LastName = "Wróbel",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111888999"
                        },
                        new
                        {
                            IdUser = new Guid("1d31a511-8d38-4223-96a0-f2b15cc90794"),
                            Email = "pawel.kaminski@example.com",
                            FirstName = "Paweł",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserLog = new Guid("32affe63-9bb3-4c86-bbf8-6d5e37c7fb3f"),
                            LastName = "Kamiński",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111999000"
                        },
                        new
                        {
                            IdUser = new Guid("655887cb-b3cd-40da-b2bb-48b5e84239f9"),
                            Email = "mar.radw@example.com",
                            FirstName = "Marcin",
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            IdUserLog = new Guid("cd9e4f1f-8edd-4488-b0da-256521a720e8"),
                            LastName = "Radwański",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48431234765"
                        },
                        new
                        {
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            Email = "marian@gmail.pl",
                            FirstName = "Marian",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserLog = new Guid("b0f3e786-f68b-46fe-8b18-f4a6e1150804"),
                            LastName = "Niewiadomski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48654123432"
                        },
                        new
                        {
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            Email = "dab@gmail.pl",
                            FirstName = "Maria",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserLog = new Guid("dbf24f67-7457-47c3-a2af-a117d8e90b00"),
                            LastName = "Dąbrowska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48231443225"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserLog", b =>
                {
                    b.Property<Guid>("IdUserLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResettingEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResettingPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResetEmailToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResetEmailTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResetPasswordToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResetPasswordTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationCodeExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUserLog")
                        .HasName("PK_UserLog");

                    b.ToTable("UserLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdUserLog = new Guid("5cb8efaa-2432-46d1-9984-b41a40bab7b3"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("2f765163-6728-48bc-9767-66687efdf86e"),
                            DateCreated = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("8312d4fd-fe6d-4001-a037-cde12000161d"),
                            DateCreated = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("e7653083-1497-4aa0-a56b-dec32a61d71f"),
                            DateCreated = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("9ae2c2f3-4ab1-4512-9832-7649d5ff61d8"),
                            DateCreated = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("5091bf83-df7d-4a54-a35b-31b44d1a1643"),
                            DateCreated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("df0a8813-0938-42a6-ac84-26298701f456"),
                            DateCreated = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("2a019dc8-fe9f-4a63-b692-49e03f889f7f"),
                            DateCreated = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("c91c99ca-fffd-42a5-9e6e-fa67d3c0f762"),
                            DateCreated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("8db9e713-d6f0-4f34-b348-c7da0c1a51d6"),
                            DateCreated = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("32affe63-9bb3-4c86-bbf8-6d5e37c7fb3f"),
                            DateCreated = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("cd9e4f1f-8edd-4488-b0da-256521a720e8"),
                            DateCreated = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("b0f3e786-f68b-46fe-8b18-f4a6e1150804"),
                            DateCreated = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserLog = new Guid("dbf24f67-7457-47c3-a2af-a117d8e90b00"),
                            DateCreated = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", "AdvertCategory")
                        .WithMany("Adverts")
                        .HasForeignKey("IdAdvertCategory")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_AdvertCategory");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", "AdvertLog")
                        .WithMany("Adverts")
                        .HasForeignKey("IdAdvertLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_AdvertLog");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("Adverts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_User");

                    b.Navigation("AdvertCategory");

                    b.Navigation("AdvertLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Review", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.Advert", "Advert")
                        .WithMany("Reviews")
                        .HasForeignKey("IdAdvert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Advert");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", "ReviewLog")
                        .WithMany("Reviews")
                        .HasForeignKey("IdReviewLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_ReviewLog");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_User");

                    b.Navigation("Advert");

                    b.Navigation("ReviewLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaLink", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", "SocialMediaName")
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("IdSocialMediaName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SocialMediaLink_SocialMediaName");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SocialMediaLink_User");

                    b.Navigation("SocialMediaName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.UserLog", "UserLog")
                        .WithMany("Users")
                        .HasForeignKey("IdUserLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserLog");

                    b.Navigation("Role");

                    b.Navigation("UserLog");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", b =>
                {
                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("Reviews");

                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserLog", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
