// <auto-generated />
using System;
using AudioEngineersPlatformBackend.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AudioEngineersPlatformBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AudioEngineersPlatformDbContext))]
    partial class AudioEngineersPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.Property<Guid>("IdAdvert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverImageKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdAdvertCategory")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAdvertLog")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAdvert")
                        .HasName("PK_Advert");

                    b.HasIndex("IdAdvertCategory");

                    b.HasIndex("IdAdvertLog");

                    b.HasIndex("IdUser");

                    b.HasIndex("Title", "Description")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "Description"), "GIN");

                    b.ToTable("Advert", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvert = new Guid("31ba89aa-f10f-40e7-b4b0-7375da567997"),
                            CoverImageKey = new Guid("df0f7b35-b8c2-4246-b7f7-ccc82d4a3a7e"),
                            Description = "Mam ponad 15 lat doświadczenia z miksowaniem utworów. Pracowałam nad największymi hitami Polskich artystów oraz z największymi gwiazdami branży audio. Wyróżniam się tym, że podchodzę indywidualnie do każdego zlecenia.Korzystam z najlepszych narzędzi oraz sprzętu analogowego. To właśnie w ten sposób mogę zapewnić Tobie świetne brzmienie w bezkonkurencyjnej cenie! Jeśli szukasz najlepszego inżyniera, to dobrze trafiłeś.Spowoduje, że nawet najgorzej brzmiące nagrania, będą brzmiały jak ze studio za milion dolarów :)",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("1b84601e-e225-4e9d-93d2-911fb0a1569e"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DZ06evO4pPsgW?si=e069a7940cc7419b",
                            Price = 350.0,
                            Title = "Zmiksuję twój utwór za bezcen!"
                        },
                        new
                        {
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            CoverImageKey = new Guid("17cf17e7-cf1d-4239-ba5a-5f8484191038"),
                            Description = "Miksem zajmuje się na codzień, pracując przy utwórach nagrywanych w Filharmonii Warszawskiej. Uczyłem się na UMCS w Warszawie i skończyłem kierunek związany z reżyserią dźwięku. Nie ograniczam się do jednego gatunku, mogę pracować nad utworami pop-owymi, jak i muzyką klasyczną, a nawet hip-hop'em. Pracowałem z artystami takimi jak: Piotr Rogucki, Organek, czy Mietek Szcześniak, dzięki nim zyskałem bardzo dużo doświadczenia w muzyce akustycznej, którą obecnie zajmuje się najwięcej.",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("a9e9762a-2a67-46f3-b371-50405a100d58"),
                            IdUser = new Guid("2254933a-66ac-4ab8-a923-25d508d8b5c0"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd?si=123456abcdef",
                            Price = 400.0,
                            Title = "Profesjonalne miksy z pod ucha specjalisty"
                        },
                        new
                        {
                            IdAdvert = new Guid("7bfd7cfa-5fde-42e2-ac56-9ee1040b708f"),
                            CoverImageKey = new Guid("2de15e61-0ab9-49eb-b5e2-cf909809d22f"),
                            Description = "Specjalizuje się w masteringu utworów, głównie dla wytwórni, ale wykonuje również indywidualne zlecenia. Pracuje hybrydowo - ze sprzętem analogowym, ale też z cyfrowymi emulacjami pluginów, tak żeby każdy utwór mógł brzmieć możliwie najlepiej. Masteringiem zajmuje się od 10 lat i ciągle staram się udoskonalać swoje umiejętności. Pracowałam ze Szpakiem, Matą i innymi topowymi artystami z Polskiego podwórka! Możesz być pewien, że utwór z pod mojej ręki, będzie brzmiał najlepiej.",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("b3d2dce1-a858-4312-937d-c56a6e0178cf"),
                            IdUser = new Guid("731c7617-9342-415d-8e06-f77ec2d56786"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWTcaP2wCKa4K?si=abcdef123456",
                            Price = 300.0,
                            Title = "Najlepszy mastering w Polsce"
                        },
                        new
                        {
                            IdAdvert = new Guid("8370e2eb-2ea0-4c4e-99e5-b9e719427f03"),
                            CoverImageKey = new Guid("cedfe8a0-0a9f-4c4a-a50f-76f9fcac396f"),
                            Description = "Cześć, jestem Tomek, jestem producentem muzycznym, który cały swój czas poświęca na odkrywanie nowych i niebanalnych brzmień. Produkcją zajmuje się od 10 lat, więc mam w tym już duży staż. Mogę dla Ciebie wyprodukować instrumentale hip-hop'owe i trap'owe. Korzystam tylko z najlepszych syntezatorów (KORG M1, Yamaha Montage M). Posiadam również szeroką gamę prawdziwych instrumentów (Banjo, Gitary akustyczne, Flety), które moge dodać do produkcji stworzonej pod twoje indywidualne potrzeby. Najlepiej pracuje mi się z pojedynczymi artystami, lecz mogę również podjąć się pracy z zespołem!",
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            IdAdvertLog = new Guid("efe85186-52c9-4c46-b585-d4b47523db47"),
                            IdUser = new Guid("29d1d9bd-87d9-4125-99a5-0f15c9df3a30"),
                            PortfolioUrl = "https://open.spotify.com/playlist/4nZo2X8iHrwhYBYdKvysgI",
                            Price = 800.0,
                            Title = "Unikatowe produkcje i instrumentale"
                        },
                        new
                        {
                            IdAdvert = new Guid("8cb96d43-a8a9-4010-8613-f721ecedb8b3"),
                            CoverImageKey = new Guid("0c318716-7c49-4735-9ce2-9eb499377e8a"),
                            Description = "Hej, jestem Michał, jestem inżynierem dźwięku, realizatorem nagrań i reżyserem dźwięku w TVP. W wolnym czasie miksuje utwory dla klientów - robię to z pasji, a nie dla pieniędzy, bo kocham to robić! Pracuje nad różnymi utworami, ale moja specjalizacja to Rock. Jestem biegły w pracy na Reaperze, ale znam również Pro Tools'a i FL Studio. Jeśli wybierzesz mnie, możesz być pewien, że twój miks będzie brzmiał dobrze niezależnie od miejsca - w samochodzie, na słuchawkach, czy w klubie!",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("24ba6029-f88c-4b12-9a63-bf00c2d9f3e4"),
                            IdUser = new Guid("3fb9e066-38b7-42ae-900c-d7ab5ae280f0"),
                            PortfolioUrl = "https://open.spotify.com/playlist/3eoncc59w7c8t1PnKtSOh6",
                            Price = 450.0,
                            Title = "Miksy z pazurem"
                        },
                        new
                        {
                            IdAdvert = new Guid("18809be2-b063-4ada-a7a4-81f9fa107322"),
                            CoverImageKey = new Guid("504cd9ce-5804-4f76-b6bf-706aae87a1b0"),
                            Description = "Cześć jestem Kasia i masteruje utwory. Miałeś kiedyś tak, że po wrzuceniu utworu na platformy streamingowe był cichy? Nie uderzał tak mocno jak inne utwory? To kwestia masteringu, albo jego braku! Jeśli nie wiesz co zrobić, to wystarczy, że do mnie napiszesz, prześlesz swoje pliki, a ja powiem Tobie co jest nie tak - dobry mastering to nie tylko kwestia dobrego masteringowca, ale też dobrego miksu. Gdyby coś było nie tak, odrazu dam Tobie znać, bo chodzi o to, żebyś miał najlepszy efekt finalny!",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("fe0d1832-793e-4cf8-983a-bbe09d7e0fa2"),
                            IdUser = new Guid("ac89f1a4-6988-4211-8136-fbf9b45e4cf2"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DX4WYpdgoIcn6?si=abcd3456ef90",
                            Price = 320.0,
                            Title = "Najgłośniejsze mastery"
                        },
                        new
                        {
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            CoverImageKey = new Guid("ef11919d-3e86-4c08-a594-03800f613fd8"),
                            Description = "Hej, specjalizuje się w produkcji instrumentali, mam w tym duże doświadczenie, bo jestem w branży już od 15 lat. Możliwe, że mnie znasz chociażby z produkcji dla Pezeta, czy Żabsona. Lubie pracować nad trapowymi produkcjami, ale nie ograniczam się tylko do nich - potrafię również robić bity pop'owe. Jeśli szukasz czegoś ciekawego, albo chciałbyś, żebym wykonał dla Ciebie produkcję inspirowaną innym utworem, wystarczy, że do mnie napiszesz, a ja poprowadzę Cię za rękę!",
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            IdAdvertLog = new Guid("993648ca-9d51-419a-85e8-046e8fc3162b"),
                            IdUser = new Guid("07434fd4-3450-4a01-a8c4-c371ed011e48"),
                            PortfolioUrl = "https://open.spotify.com/playlist/2UZk7JjJnbTut1w8fqs3JL",
                            Price = 900.0,
                            Title = "Trapowe bity"
                        },
                        new
                        {
                            IdAdvert = new Guid("33545021-1ffb-4f46-9df8-6242b8f0786f"),
                            CoverImageKey = new Guid("d98dd161-cd11-4397-b6b2-48a5656c20a3"),
                            Description = "Cześć, jestem inżynierem audio, który dobrze wie, co zrobić, żeby twój utwór brzmiał najlepiej. Pracuje tylko z najlepszymi emulacjami sprzętu analogowego (UAD, Slate i Waves) i bardzo cenie sobie dobrą organizację pracy. Preferuje pracę z klientami, którzy potrafią mi trafnie wypunktować poprawki do utworów, nad którymi pracujemy, dlatego proszę też, abyś liczył się z tym, że nie będę z Tobą pracować, jeśli nie będziesz potrafił/a tego zaakceptować. Jeśli szukasz profesjonalisty, trafiłeś idealnie! ",
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            IdAdvertLog = new Guid("c8ab7e20-e7dd-4616-8862-d15dad3c986a"),
                            IdUser = new Guid("e07bc534-3324-4af4-8d97-faee7242e896"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWXRqgorJj26U?si=4567abcd1234",
                            Price = 480.0,
                            Title = "Basowe miksy :)"
                        },
                        new
                        {
                            IdAdvert = new Guid("a79c87d0-276b-48bd-b23c-9af67afd4c41"),
                            CoverImageKey = new Guid("c2363242-295c-4435-867c-90d9b96b085a"),
                            Description = "Cześć, jestem Paweł, masteruje piosenki już 5 lat. Wiem, że to niedużo, ale zaufaj mi, że dobrze wiem co robię. Troche o mnie - jestem absolwentem Akademii Realizacji Dźwięku w Warszawie (2020 rok ukończenia) i doskonale wiem, co to znaczy profesjonalny master. Przez długi czas pracowałem jak estradowiec, głównie na koncertach rock'owych, dlatego też, wiem jak ważne jest dobry mastering utworu - jeśli jest słaby, to utwór będzie brzmiał kiepsko na koncercie. Serdecznie zapraszam Cię do współpracy, razem zrobimy coś świetnego!",
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            IdAdvertLog = new Guid("70820368-d390-4c01-af1f-9e7b8e8413d2"),
                            IdUser = new Guid("1d31a511-8d38-4223-96a0-f2b15cc90794"),
                            PortfolioUrl = "https://open.spotify.com/playlist/37i9dQZF1DWY4xHQp97fN6?si=bcdef7890123",
                            Price = 350.0,
                            Title = "Mastering na poziomie!"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", b =>
                {
                    b.Property<Guid>("IdAdvertCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAdvertCategory")
                        .HasName("PK_AdvertCategory");

                    b.ToTable("AdvertCategory", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvertCategory = new Guid("e6ddd487-8b56-4c8f-b289-2f04babbabda"),
                            CategoryName = "Mixing"
                        },
                        new
                        {
                            IdAdvertCategory = new Guid("80c20081-c580-4aaf-a346-2587ccfdebf5"),
                            CategoryName = "Mastering"
                        },
                        new
                        {
                            IdAdvertCategory = new Guid("b8785564-e008-4889-b633-7f5d3558eb92"),
                            CategoryName = "Production"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", b =>
                {
                    b.Property<Guid>("IdAdvertLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("IdAdvertLog")
                        .HasName("PK_AdvertLog");

                    b.ToTable("AdvertLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdAdvertLog = new Guid("1b84601e-e225-4e9d-93d2-911fb0a1569e"),
                            DateCreated = new DateTime(2024, 2, 3, 12, 35, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("a9e9762a-2a67-46f3-b371-50405a100d58"),
                            DateCreated = new DateTime(2024, 5, 14, 15, 51, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("b3d2dce1-a858-4312-937d-c56a6e0178cf"),
                            DateCreated = new DateTime(2025, 2, 6, 17, 35, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("efe85186-52c9-4c46-b585-d4b47523db47"),
                            DateCreated = new DateTime(2025, 5, 3, 12, 5, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("24ba6029-f88c-4b12-9a63-bf00c2d9f3e4"),
                            DateCreated = new DateTime(2025, 6, 12, 9, 23, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("fe0d1832-793e-4cf8-983a-bbe09d7e0fa2"),
                            DateCreated = new DateTime(2025, 6, 23, 22, 25, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("993648ca-9d51-419a-85e8-046e8fc3162b"),
                            DateCreated = new DateTime(2025, 8, 13, 23, 12, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("c8ab7e20-e7dd-4616-8862-d15dad3c986a"),
                            DateCreated = new DateTime(2025, 9, 3, 12, 11, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdAdvertLog = new Guid("70820368-d390-4c01-af1f-9e7b8e8413d2"),
                            DateCreated = new DateTime(2025, 5, 13, 6, 22, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.HubConnection", b =>
                {
                    b.Property<Guid>("IdHubConnection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.HasKey("IdHubConnection")
                        .HasName("PK_Connection");

                    b.HasIndex("IdUser");

                    b.ToTable("HubConnection", (string)null);
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileKey")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.HasKey("IdMessage")
                        .HasName("PK_Message");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdAdvert")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdReviewLog")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<byte>("SatisfactionLevel")
                        .HasColumnType("smallint");

                    b.HasKey("IdReview")
                        .HasName("PK_Review");

                    b.HasIndex("IdAdvert");

                    b.HasIndex("IdReviewLog");

                    b.HasIndex("IdUser");

                    b.ToTable("Review", (string)null);

                    b.HasData(
                        new
                        {
                            IdReview = new Guid("dbe3112c-8914-44b1-8011-d58cb2ba4270"),
                            Content = "Krzysiek dobrze wie co robi, zna się na rzeczy, dlatego też moja ocena to 5! Już pierwsza wersją miksu mi się podobała :)",
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            IdReviewLog = new Guid("d9de48fd-0abc-4b52-8371-f9f6959fdc46"),
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("f88cb211-6464-4b28-aa48-75f257624d86"),
                            Content = "Super miks, Krzychu zna się na rzeczy, w mojej opinii nie ma nikogo lepszego od niego w branży!",
                            IdAdvert = new Guid("72ac8a29-19e2-4b7b-b810-418d638b5356"),
                            IdReviewLog = new Guid("1f642c35-dbfb-4062-ae75-7cf0e3f27f6f"),
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("649406c7-a59a-4102-b7cb-c39d16bc7117"),
                            Content = "Praca z Piotrem to czysta przyjemność, poinstruował mnie jak wysyłać mu pliki, a sam miks wysłał mi bardzo szybko.",
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            IdReviewLog = new Guid("9473bb77-cff3-42d7-bd0e-2807aa2fef52"),
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("fbd98612-7ccd-4b83-afaa-7084e758e746"),
                            Content = "Ehh, strasznie arogancki gość, jeśli chcesz stracić czas to trafiłeś super, bez komentarza...",
                            IdAdvert = new Guid("aff251d8-9e58-4f5c-ba43-4c6597fc8a08"),
                            IdReviewLog = new Guid("0d38bc51-218b-4e12-8e39-6bef8654419b"),
                            IdUser = new Guid("655887cb-b3cd-40da-b2bb-48b5e84239f9"),
                            SatisfactionLevel = (byte)1
                        },
                        new
                        {
                            IdReview = new Guid("2d7fe610-9fb0-4a8e-923c-2f7a8afe2a78"),
                            Content = "Polecam każdemu, kto chce mieć master na szybko, w przystępnej cenie i dobrej jakości.",
                            IdAdvert = new Guid("7bfd7cfa-5fde-42e2-ac56-9ee1040b708f"),
                            IdReviewLog = new Guid("39cc7997-692f-40f4-a3ec-68b00940f6a6"),
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            SatisfactionLevel = (byte)4
                        },
                        new
                        {
                            IdReview = new Guid("5f3bcc4b-d484-44cc-baa2-339373b7d0f0"),
                            Content = "Piękna produkcja! Naprawdę jestem w szoku, że tak szybko dostałem już w pełni gotowego bita, mega!",
                            IdAdvert = new Guid("8370e2eb-2ea0-4c4e-99e5-b9e719427f03"),
                            IdReviewLog = new Guid("60bb7ac9-88de-4bd4-933b-ce3e71d9cb45"),
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            SatisfactionLevel = (byte)5
                        },
                        new
                        {
                            IdReview = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6"),
                            Content = "Miks był okej, ale miałem nadzieje, że Ania bardziej przyłoży się do przeczyszczenia ścieżek, na których było dużo pogłosu!",
                            IdAdvert = new Guid("31ba89aa-f10f-40e7-b4b0-7375da567997"),
                            IdReviewLog = new Guid("3461a295-b612-4526-aaf1-205ea3a6beff"),
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            SatisfactionLevel = (byte)3
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("IdReviewLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("IdReviewLog")
                        .HasName("PK_ReviewLog");

                    b.ToTable("ReviewLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdReviewLog = new Guid("d9de48fd-0abc-4b52-8371-f9f6959fdc46"),
                            DateCreated = new DateTime(2025, 3, 13, 15, 48, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("1f642c35-dbfb-4062-ae75-7cf0e3f27f6f"),
                            DateCreated = new DateTime(2025, 5, 7, 13, 23, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("9473bb77-cff3-42d7-bd0e-2807aa2fef52"),
                            DateCreated = new DateTime(2025, 4, 17, 22, 21, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("0d38bc51-218b-4e12-8e39-6bef8654419b"),
                            DateCreated = new DateTime(2025, 4, 29, 21, 17, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("39cc7997-692f-40f4-a3ec-68b00940f6a6"),
                            DateCreated = new DateTime(2025, 2, 16, 13, 11, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("60bb7ac9-88de-4bd4-933b-ce3e71d9cb45"),
                            DateCreated = new DateTime(2025, 5, 26, 15, 42, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            IdReviewLog = new Guid("3461a295-b612-4526-aaf1-205ea3a6beff"),
                            DateCreated = new DateTime(2025, 4, 24, 19, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRole")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            RoleName = "Administrator"
                        },
                        new
                        {
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            RoleName = "Client"
                        },
                        new
                        {
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            RoleName = "Audio engineer"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaLink", b =>
                {
                    b.Property<Guid>("IdSocialMediaLink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSocialMediaName")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSocialMediaLink")
                        .HasName("PK_SocialMediaLink");

                    b.HasIndex("IdSocialMediaName");

                    b.HasIndex("IdUser");

                    b.ToTable("SocialMediaLink", (string)null);

                    b.HasData(
                        new
                        {
                            IdSocialMediaLink = new Guid("8c0d3528-e2cb-430a-bfd4-8e0623c714cf"),
                            IdSocialMediaName = new Guid("02c8722f-dccc-4060-bec3-c95815c67703"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.instagram.com/prod.mustang/"
                        },
                        new
                        {
                            IdSocialMediaLink = new Guid("7667e3a7-e8f9-4049-af10-a0a405dacf40"),
                            IdSocialMediaName = new Guid("371dbd6d-76eb-4266-aaa3-2b431c5cbafe"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.facebook.com/prod.mustangg/"
                        },
                        new
                        {
                            IdSocialMediaLink = new Guid("b5b570dd-43c8-471e-976b-91a0d50de9f5"),
                            IdSocialMediaName = new Guid("4639c978-26fc-4027-b036-3fc5c0d1d221"),
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Url = "https://www.linkedin.com/in/stanisław-stepka/"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", b =>
                {
                    b.Property<Guid>("IdSocialMediaName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSocialMediaName")
                        .HasName("PK_SocialMediaName");

                    b.ToTable("SocialMediaName", (string)null);

                    b.HasData(
                        new
                        {
                            IdSocialMediaName = new Guid("02c8722f-dccc-4060-bec3-c95815c67703"),
                            Name = "Instagram"
                        },
                        new
                        {
                            IdSocialMediaName = new Guid("371dbd6d-76eb-4266-aaa3-2b431c5cbafe"),
                            Name = "Facebook"
                        },
                        new
                        {
                            IdSocialMediaName = new Guid("4639c978-26fc-4027-b036-3fc5c0d1d221"),
                            Name = "Linkedin"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdToken");

                    b.HasIndex("IdUser");

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUserAuthLog")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUser")
                        .HasName("PK_User");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_User_ForCheckAuth");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("IdUser"), new[] { "Email", "FirstName", "LastName", "PhoneNumber", "IdRole" });

                    b.HasIndex("IdUserAuthLog");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("aebc2724-0edf-4691-99e9-65cbd3aab3bf"),
                            Email = "dominik.kow@gmail.com",
                            FirstName = "Dominik",
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            IdUserAuthLog = new Guid("5cb8efaa-2432-46d1-9984-b41a40bab7b3"),
                            LastName = "Kowalski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48123456789"
                        },
                        new
                        {
                            IdUser = new Guid("5bfc9c8d-4789-4065-99d9-81ec5b58c0f5"),
                            Email = "jan.nowak@gmail.com",
                            FirstName = "Jan",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserAuthLog = new Guid("2f765163-6728-48bc-9767-66687efdf86e"),
                            LastName = "Nowak",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48696432123"
                        },
                        new
                        {
                            IdUser = new Guid("828daa53-9a49-40ad-97b3-31b0349bc08d"),
                            Email = "anna.kow@gmail.com",
                            FirstName = "Anna",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("8312d4fd-fe6d-4001-a037-cde12000161d"),
                            LastName = "Kowalska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48543123123"
                        },
                        new
                        {
                            IdUser = new Guid("2254933a-66ac-4ab8-a923-25d508d8b5c0"),
                            Email = "piotr.nowak@gmail.com",
                            FirstName = "Piotr",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("e7653083-1497-4aa0-a56b-dec32a61d71f"),
                            LastName = "Nowak",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111222333"
                        },
                        new
                        {
                            IdUser = new Guid("731c7617-9342-415d-8e06-f77ec2d56786"),
                            Email = "ewa.maj@gmail.com",
                            FirstName = "Ewa",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("9ae2c2f3-4ab1-4512-9832-7649d5ff61d8"),
                            LastName = "Maj",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111333444"
                        },
                        new
                        {
                            IdUser = new Guid("29d1d9bd-87d9-4125-99a5-0f15c9df3a30"),
                            Email = "tomasz.zielinski@gmail.com",
                            FirstName = "Tomasz",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("5091bf83-df7d-4a54-a35b-31b44d1a1643"),
                            LastName = "Zieliński",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111444555"
                        },
                        new
                        {
                            IdUser = new Guid("3fb9e066-38b7-42ae-900c-d7ab5ae280f0"),
                            Email = "michal.wojcik@gmail.com",
                            FirstName = "Michał",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("df0a8813-0938-42a6-ac84-26298701f456"),
                            LastName = "Wójcik",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111555666"
                        },
                        new
                        {
                            IdUser = new Guid("ac89f1a4-6988-4211-8136-fbf9b45e4cf2"),
                            Email = "katarzyna.wisniewska@gmail.com",
                            FirstName = "Katarzyna",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("2a019dc8-fe9f-4a63-b692-49e03f889f7f"),
                            LastName = "Wiśniewska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111666777"
                        },
                        new
                        {
                            IdUser = new Guid("07434fd4-3450-4a01-a8c4-c371ed011e48"),
                            Email = "krzysztof.lewandowski@gmail.com",
                            FirstName = "Krzysztof",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("c91c99ca-fffd-42a5-9e6e-fa67d3c0f762"),
                            LastName = "Lewandowski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111777888"
                        },
                        new
                        {
                            IdUser = new Guid("e07bc534-3324-4af4-8d97-faee7242e896"),
                            Email = "agnieszka.wrobel@gmail.com",
                            FirstName = "Agnieszka",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("8db9e713-d6f0-4f34-b348-c7da0c1a51d6"),
                            LastName = "Wróbel",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111888999"
                        },
                        new
                        {
                            IdUser = new Guid("1d31a511-8d38-4223-96a0-f2b15cc90794"),
                            Email = "pawel.kaminski@gmail.com",
                            FirstName = "Paweł",
                            IdRole = new Guid("522c6700-165e-4189-b234-9fb533266e07"),
                            IdUserAuthLog = new Guid("32affe63-9bb3-4c86-bbf8-6d5e37c7fb3f"),
                            LastName = "Kamiński",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48111999000"
                        },
                        new
                        {
                            IdUser = new Guid("655887cb-b3cd-40da-b2bb-48b5e84239f9"),
                            Email = "mar.radw@gmail.com",
                            FirstName = "Marcin",
                            IdRole = new Guid("d92d29b8-f462-46df-8efb-de6b9aa5109a"),
                            IdUserAuthLog = new Guid("cd9e4f1f-8edd-4488-b0da-256521a720e8"),
                            LastName = "Radwański",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48431234765"
                        },
                        new
                        {
                            IdUser = new Guid("fdf7bda4-f40f-484f-bc40-adbf8aa98985"),
                            Email = "marian@gmail.com",
                            FirstName = "Marian",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserAuthLog = new Guid("b0f3e786-f68b-46fe-8b18-f4a6e1150804"),
                            LastName = "Niewiadomski",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48654123432"
                        },
                        new
                        {
                            IdUser = new Guid("156765b0-84a0-4389-af75-78f2f36dea04"),
                            Email = "dab@gmail.com",
                            FirstName = "Maria",
                            IdRole = new Guid("004865e2-177f-4c54-bb4c-69799f0bf315"),
                            IdUserAuthLog = new Guid("dbf24f67-7457-47c3-a2af-a117d8e90b00"),
                            LastName = "Dąbrowska",
                            Password = "AQAAAAIAAYagAAAAEFIagC5C9vbbJvt0Laj4EFwEie4imyDjDa7Ug56CJY8hKm9ftbEdPRtKo/dXKkW3cQ==",
                            PhoneNumber = "+48231443225"
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserAuthLog", b =>
                {
                    b.Property<Guid>("IdUserAuthLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemindingPassword")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResettingEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResettingPassword")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.HasKey("IdUserAuthLog")
                        .HasName("PK_UserAuthLog");

                    b.ToTable("UserAuthLog", (string)null);

                    b.HasData(
                        new
                        {
                            IdUserAuthLog = new Guid("5cb8efaa-2432-46d1-9984-b41a40bab7b3"),
                            DateCreated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("2f765163-6728-48bc-9767-66687efdf86e"),
                            DateCreated = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("8312d4fd-fe6d-4001-a037-cde12000161d"),
                            DateCreated = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("e7653083-1497-4aa0-a56b-dec32a61d71f"),
                            DateCreated = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("9ae2c2f3-4ab1-4512-9832-7649d5ff61d8"),
                            DateCreated = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("5091bf83-df7d-4a54-a35b-31b44d1a1643"),
                            DateCreated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("df0a8813-0938-42a6-ac84-26298701f456"),
                            DateCreated = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("2a019dc8-fe9f-4a63-b692-49e03f889f7f"),
                            DateCreated = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("c91c99ca-fffd-42a5-9e6e-fa67d3c0f762"),
                            DateCreated = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("8db9e713-d6f0-4f34-b348-c7da0c1a51d6"),
                            DateCreated = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("32affe63-9bb3-4c86-bbf8-6d5e37c7fb3f"),
                            DateCreated = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("cd9e4f1f-8edd-4488-b0da-256521a720e8"),
                            DateCreated = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("b0f3e786-f68b-46fe-8b18-f4a6e1150804"),
                            DateCreated = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        },
                        new
                        {
                            IdUserAuthLog = new Guid("dbf24f67-7457-47c3-a2af-a117d8e90b00"),
                            DateCreated = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRemindingPassword = false,
                            IsResettingEmail = false,
                            IsResettingPassword = false,
                            IsVerified = true
                        });
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserMessage", b =>
                {
                    b.Property<Guid>("IdUserMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMessage")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUserRecipient")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUserSender")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.HasKey("IdUserMessage")
                        .HasName("PK_UserMessage");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdUserRecipient");

                    b.HasIndex("IdUserSender");

                    b.ToTable("UserMessage", (string)null);
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", "AdvertCategory")
                        .WithMany("Adverts")
                        .HasForeignKey("IdAdvertCategory")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_AdvertCategory");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", "AdvertLog")
                        .WithMany("Adverts")
                        .HasForeignKey("IdAdvertLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_AdvertLog");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("Adverts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Advert_User");

                    b.Navigation("AdvertCategory");

                    b.Navigation("AdvertLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.HubConnection", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("HubConnections")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HubConnection_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Review", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.Advert", "Advert")
                        .WithMany("Reviews")
                        .HasForeignKey("IdAdvert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Advert");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", "ReviewLog")
                        .WithMany("Reviews")
                        .HasForeignKey("IdReviewLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_ReviewLog");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Review_User");

                    b.Navigation("Advert");

                    b.Navigation("ReviewLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaLink", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", "SocialMediaName")
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("IdSocialMediaName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SocialMediaLink_SocialMediaName");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("SocialMediaLinks")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SocialMediaLink_User");

                    b.Navigation("SocialMediaName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Token", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.UserAuthLog", "UserAuthLog")
                        .WithMany("Users")
                        .HasForeignKey("IdUserAuthLog")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserLog");

                    b.Navigation("Role");

                    b.Navigation("UserAuthLog");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserMessage", b =>
                {
                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.Message", "Message")
                        .WithMany("UserMessages")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserMessage_Message");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "UserRecipient")
                        .WithMany("UserMessagesRecipient")
                        .HasForeignKey("IdUserRecipient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserMessage_UserRecipient");

                    b.HasOne("AudioEngineersPlatformBackend.Domain.Entities.User", "UserSender")
                        .WithMany("UserMessagesSender")
                        .HasForeignKey("IdUserSender")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserMessage_UserSender");

                    b.Navigation("Message");

                    b.Navigation("UserRecipient");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Advert", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertCategory", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.AdvertLog", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Message", b =>
                {
                    b.Navigation("UserMessages");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.ReviewLog", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.SocialMediaName", b =>
                {
                    b.Navigation("SocialMediaLinks");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("HubConnections");

                    b.Navigation("Reviews");

                    b.Navigation("SocialMediaLinks");

                    b.Navigation("Tokens");

                    b.Navigation("UserMessagesRecipient");

                    b.Navigation("UserMessagesSender");
                });

            modelBuilder.Entity("AudioEngineersPlatformBackend.Domain.Entities.UserAuthLog", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
